/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mylibrary;

import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author 91930
 */
public class History extends javax.swing.JFrame {

    /**
     * Creates new form History
     */
    public History() {
        initComponents();
        
//       tablehistory.setBackground (new Color (0,0,0,0));
//
//((DefaultTableCellRenderer) tablehistory.getDefaultRenderer(Object.class)).setBackground (new Color (0,0,0,0));
//
//tablehistory.setGridColor (Color.WHITE);
//
//tablehistory.setForeground (Color.WHITE);
//
//scrollpanehistory.setBackground (new Color (0,0,0,0));
//
//scrollpanehistory.setOpaque (false);
//tablehistory.setOpaque (false);
//((DefaultTableCellRenderer) tablehistory.getDefaultRenderer(Object.class)).setOpaque(false);
//
//scrollpanehistory.getViewport().setOpaque (false);
//
//
//tablehistory.setShowGrid (true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scrollpanehistory = new javax.swing.JScrollPane();
        tablehistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/add.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 70, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/reply.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 70, 70));

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("History Books");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 310, 80));

        tablehistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Mudrarakshasa", "2017", "305", "ishakhadatta "},
                {"Ancient India", "2017", "370", " RC Majumdar"},
                {"The Hidden Hindu", "2022", "256", "Akshat Gupta"},
                {"Vijayanagara", "2019", "126", "S.R. RAMANUJAN"},
                {"VALMIKI RAMAYAN", " 300 bce", "588", "Valmiki"},
                {"Mrutyunjay", "2012", "628", "Shivaji Sawant"},
                {"Sankshipt Itihas", "2016", "269", "Burnwal Mahesh Kumar"},
                {"Sapiens: A Brief History Of Humankind  ", "2011", "512", " YUVAL NOAH HARARI"},
                {"Mein Kampf", "1925", "530", "Hitler Adolf"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book Name", "Published Date", "Pages", "Auther"
            }
        ));
        tablehistory.setRowHeight(40);
        tablehistory.setRowSelectionAllowed(false);
        scrollpanehistory.setViewportView(tablehistory);

        jPanel1.add(scrollpanehistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 490, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/h3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new Library().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollpanehistory;
    private javax.swing.JTable tablehistory;
    // End of variables declaration//GEN-END:variables
}
